name: List services in GCP
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.8.3'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'github-provider'
          service_account: "github-federation"
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud iam workload-identity-pools list --location="global" --show-deleted --project favorable-tree-366516
