name: List services in GCP
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1.0.0

      with:
          workload_identity_provider: 'projects/31676311622/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: "github-federation@favorable-tree-366516.iam.gserviceaccount.com"

    - name: 'Use gcloud CLI'
      run: | 
        gcloud info
        gcloud config set project 31676311622

    - name: create secret
      run: |
        echo -n "Demo" | gcloud secrets create password --data-file=-