name: List services in GCP
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.8.3'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/31676311622/locations/global/workloadIdentityPools/github-pool/attribute.repository/SEP6-A2022/SEP6'
          service_account: "github-federation@favorable-tree-366516.iam.gserviceaccount.com"
          audience: //iam.googleapis.com/projects/31676311622/locations/global/workloadIdentityPools/github-pool/*
    - id: 'gcloud'
      name: 'gcloud'
      run: |
        gcloud iam workload-identity-pools list --location="global" --show-deleted --project favorable-tree-366516
