name: List services in GCP
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  

jobs:
  Pulumi_preview:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1.0.0
      with:
          workload_identity_provider: 'projects/31676311622/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: "github-federation@favorable-tree-366516.iam.gserviceaccount.com"
          token_format: 'access_token'
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Pulumi preview
      working-directory: src
      env:
        PULUMI_CONFIG_PASSPHRASE: ""
      run: |
        pulumi login gs://sep6-a2022
        pulumi stack select dev
        pulumi preview